### ISSUE TITLE
Are genomic coordinates in bed file comparable to ensembl coordinates?

### ISSUE THREAD

**Issue by jsleight1** [mnahinkhan/rnpfind#1]
Currently it is a little confusing as to whether the genomic coordinates returned from all 3 data sources (attract, postar and rbpdb)
are comparable against ensembl due to the [displacement] variable (https://github.com/mnahinkhan/rnpfind/blob/dev/cli/src/rnpfind/populate_rbp_binding_sites_script.py#L41) applied. 

As far as I understand the binding sites reported following sequence screening using [pwm_scan](https://github.com/mnahinkhan/rnpfind/blob/dcf4038cb08905c03926974e370cfb5d6ce408f1/cli/src/rnpfind/pwm_scan.py#L223) are 0 based e.g. a binding site 1-5 binds from the 2nd to the 6th base of the sequence inclusive. 

However I'm unsure as to whether the displacement variable applied to convert this into a genomic coordinate is correct?

In addition does the returned genomic start need be + 1 to compare against ensembl coordinates due to ensembl being 1 based not 0 based (https://m.ensembl.org/Help/Faq?id=286)

**Comment by mnahinkhan** [comment]
Hey!

Thanks so much for your interest in the project. I never thought anyone would use this, so this is a pleasant surprise :P


## Boring Details

Your question made me motivated to finally go through the project and fix all the one-off errors for each of the data sources.

For your reference, here are two useful sites that explain the 1-based (fully closed) and 0-based (half-open) systems really well:
https://www.biostars.org/p/84686/
https://genome-blog.soe.ucsc.edu/blog/2016/12/12/the-ucsc-genome-browser-coordinate-counting-systems/


The key take-aways of the above two are:
 - BED files are meant to be 0-based, half open.
 - But when UCSC Genome Browser shows coordinates, they show it in 1-based, fully-closed system.
 - Ensembl is in 1-based, fully-closed coordinates
 - When people show coordinates like: "chr1:19000-20000", with colons and dashes, they usually mean 1-based, fully closed
 - When people show coordinates like: "chr1  18999  20000", with spaces or tabs, they usually mean 0-based, half open.


Since `rnpfind` outputs BED files, I've decided to stick to 0-based, half open outputs for the BED file outputs.

In case of input though, I've been using sources that use "chrX:start-end" style, so the input is treated as 1-based, fully closed. 



I have gone through each of the data sources manually and realized there were one off errors here and there. 

I have fixed them all now. You can see the changes for yourself if you're interested:

https://github.com/mnahinkhan/rnpfind/commit/1338cf12916ef391ac14e29f05cd5462325ecad2


## Relevant to you!
All of the above is just to say that `rnpfind` (v 1.1.0) should hopefully now output the correct binding site coordinates for all data sources, with respect to the BED file format standards (0-based, half open).


Now if you are comparing these sites against those described in the ENSEMBL system, you will have to either convert the sites you get from `rnpfind` or those from Ensemble, as you see fit.

Take a look at https://www.biostars.org/p/84686/ to see how to do the conversion!

Do let me know if you need help or clarification on any of this, and good luck with your endeavors!

**Comment by mnahinkhan** [comment]
Yes, I think you should just add +1 to the start of the binding sites returned by rnpfind to compare to Ensembl

**Comment by jsleight1** [comment]
Thank you very much for getting back to this. This has clarified my questions and it looks like my results are starting to match up now with the updates.
